<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Macademy\Blog\ViewModel\Post $postVm */
$postVm = $block->getData('post_vm');
$post = $postVm->getDetail();
?>

<div class="blog-post-detail">
    <h1> <?= $escaper->escapeHtml($post->getTitle()) ?> </h1>
    <p><em><?= __('Create at %1', $escaper->escapeHtml($post->getCreatedAt(), ['em', 'p', 'strong'])) ?></em></p>
    <p><?= $post->getContent() ?></p>
</div>
